url: "https://coreyrowe.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Corey's Corner" # the name of your site, e.g. ACME Corp.
