url: "https://coreyrowe.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Corey's Corner" # the name of your site, e.g. ACME Corp.

# TODO: Add Google Analytics tracking ID before deploying to production
google_analytics: ""

excerpt_separator: <!-- excerpt-end -->

collections:
  topics:
    output: true

defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope: # Used to serve images pulled from Medium archive. Credit: https://github.com/Donohue/medium-to-jekyll
      path: "img"
    values:
      image: true
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-redirect-from