url: "https://coreyrowe.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Corey's Corner" # the name of your site, e.g. ACME Corp.

# TODO: Add Google Analytics tracking ID before deploying to production
google_analytics: ""

collections:
  topics:
    output: true

defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"